version: "3"

services:
  db:
    image: postgres:14.3-alpine
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - db:/var/lib/postgresql/data
    restart: always